
<?php
global $zon, $site_url;
$user_ip = $_SERVER['REMOTE_ADDR'];
$data = [];
if (isset($zon['page'][1])) {
    $game_name = urldecode(str_replace("-", " ", $zon['page'][1]));
    $data = dataBy("SELECT * FROM zon_games WHERE game_name='$game_name'")[0];
    $game_id = $data['id'];
}

// if(empty($data)) {
//     echo "<script>window.location.href = '/404'</script>";
// }


ini_set('display_errors', 0);
error_reporting(E_ALL);

?>
<script>
    poki = {
        game_id: <?= $data['id'] ?>,
        game_name: "<?= $data['game_name'] ?>",
        url: "<?= $site_url ?>"
    }

</script>

<!-- Embedded Game -->
<div class="game-embed">
  <!-- <iframe 
    src="<?php echo $site_url ?>themes/portal/games/hextris/hextris-gh-pages/index.html" 
    title="Game Frame" 
    width="100%" 
    height="500px" 
    frameborder="0" 
    allowfullscreen>
  </iframe> -->
  <!-- <iframe id="game" src="https://play.gamepix.com/2048/embed?sid=e4515" frameborder="0"></iframe> -->
    <iframe id="game" src="https://play.gamepix.com/cerkio/embed?sid=e4515" frameborder="0"></iframe>
</div>

<!-- Similar Games -->
<div class="similar-games">
  <h3>Similar Games</h3>
  <div class="game-list">
    <div class="game-card">
      <img src="<?php echo $site_url ?>themes/portal/assets/images/airplane.png" alt="Game 1">
      <p>Game 1</p>
    </div>
    <div class="game-card">
      <img src="<?php echo $site_url ?>themes/portal/assets/images/airplane.png" alt="Game 2">
      <p>Game 2</p>
    </div>
    <div class="game-card">
      <img src="<?php echo $site_url ?>themes/portal/assets/images/airplane.png" alt="Game 3">
      <p>Game 3</p>
    </div>
  </div>
</div>
