<?php global $zon, $site_url; ?>
<h2>Best Games Selected By Us</h2>
<div class="game-list" id="best-games">
  <div class="game-card">
    <a href="description">
      <img src="<?php echo $site_url ?>themes/portal/assets/airplane.png" alt="Airplane Battle">
      <p>Airplane Battle</p>
    </a>
  </div>
</div>
<h2>More Games</h2>
<div id="more-games" class="game-list">
  <!-- Additional games will appear here -->
  <div class="game-card fade-in">
    <a href="description">
      <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
      <p>Car Shooting Rival Rage</p>
    </a>
  </div>
  <div class="game-card fade-in">
    <a href="description">
    <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
    <p>The Lost Joystick</p>
    </a>
  </div>
</div>
  
    