<?php global $zon, $site_url; ?>
<h2>Best Games Selected By Us</h2>
<div class="game-list" id="best-games">
<div class="game-card">
  <a href="<?php echo $site_url ?>description">
    <img src="<?php echo $site_url ?>themes/portal/assets/airplane.png" alt="Airplane Battle">
    <p>Airplane Battle</p>
  </a>
</div>
<div class="game-card">
  <a href="<?php echo $site_url ?>description">
    <img src="<?php echo $site_url ?>themes/portal/assets/boat.png" alt="Speedy Boat">
    <p>Speedy Boat</p>
  </a>
</div>
<div class="game-card">
  <a href="<?php echo $site_url ?>description">
    <img src="<?php echo $site_url ?>themes/portal/assets/galaxy.png" alt="Basket Ball">
    <p>Galaxy Battle</p>
  </a>
</div>  
<div class="game-card">
  <a href="<?php echo $site_url ?>description">
    <img src="<?php echo $site_url ?>themes/portal/assets//microtank.png" alt="Tank Battle">
    <p>Tank Battle</p>
  </a>
</div>
</div>
<h2>More Games</h2>
<div id="more-games" class="game-list">
  <!-- Additional games will appear here -->
  <div class="game-card fade-in">
    <a href="<?php echo $site_url ?>description">
      <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
      <p>Car Shooting Rival Rage</p>
    </a>
  </div>
  <div class="game-card fade-in">
    <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
    <p>Zombie Road</p>
  </div>
  <div class="game-card fade-in">
    <a href=".../CompStruc/description/description.html">
    <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
    <p>The Lost Joystick</p>
    </a>
  </div>
  <div class="game-card fade-in">
    <img src="<?php echo $site_url ?>themes/portal/assets/image-example.jpg" alt="Game Thumbnail">
    <p>Physics Box</p>
  </div>
  
    